### PR TITLE
[FLINK-30359][es] flink-sql-connector-elasticsearch6's jar should luding the dependency of com.carrotsearch:hppc

### PR DESCRIPTION
**Pull request by reswqa**

### CODE REVIEW

**Comment by reswqa** [comment]
cc @zentol

**Review by MartijnVisser — APPROVED** [review]
LGTM

**Comment by MartijnVisser** [comment]
@reswqa Can you check the CI results and fix them?

**Comment by reswqa** [comment]
@MartijnVisser Thanks for the review, I have relocation the dependency of `com.carrotsearch.hppc` and rebase this commit . It seems that first-time contributors need a maintainer to approve running workflows.

**Comment by reswqa** [comment]
@MartijnVisser CI is green, and do we need to backport this commit to the 3.0 branch?

**Comment by reswqa** [comment]
What's the progress of this pr, whether it can be merged?

**Pull request merged**
