### PR TITLE
[Flink-26884][draft] move elasticsearch connectors to the external repo

### PR DESCRIPTION
**Pull request by JingGe**
## What is the purpose of the change

**Attention**: this PR is still under construction with following tasks:
1. merge the change of #18634
2. remove all code and test related to legacy SouceFunction/SinkFunction.

With this PR, Elasticsearch connectors will be moved to the external repo.

## Brief change log

  -  create a new maven project and migrate the most part of the Flink maven pom.
  -  migrate `flink-connector-elasticsearch-base`, `flink-connector-elasticsearch6`, `flink-connector-elasticsearch7` 
  -  migrate uber for SQL: ` flink-sql-connector-elasticsearch6`, `flink-sql-connector-elasticsearch7` 
  -  some dependency bugs fix to make the compile and test passed

## Verifying this change

It can be verified by checking if "mvn clean package" works successfully.

### CODE REVIEW

**Comment by MartijnVisser** [comment]
@JingGe Thanks for this! Should we also be able to run `mvn clean install` ? I've tried that, but I'm getting getting some errors:

```
```

**Comment by JingGe** [comment]
> @JingGe Thanks for this! Should we also be able to run `mvn clean install` ? I've tried that, but I'm getting getting some errors:

looks like a Java version issue with the `InaccessibleObjectException`. Which Java version did you use while running the script?

**Comment by MartijnVisser** [comment]
> > @JingGe Thanks for this! Should we also be able to run `mvn clean install` ? I've tried that, but I'm getting getting some errors:
> 
> looks like a Java version issue with the `InaccessibleObjectException`. Which Java version did you use while running the script?

```
java -version    

openjdk version "1.8.0_322"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (Temurin)(build 25.322-b06, mixed mode)
```

**Comment by zentol** [comment]
@MartijnVisser Based on the stack trace you're using Java 11. See what `mvn --version` says (which relies on JAVA_HOME).

**Comment by MartijnVisser** [comment]
> mvn --version

That's the weird part, that shows Java 8

```
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T18:29:23+01:00)
Maven home: /usr/local/Cellar/maven@3.2/3.2.5_1/libexec
Java version: 1.8.0_322, vendor: Temurin
Java home: /Users/martijnvisser/.sdkman/candidates/java/8.0.322-tem/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

However, after a Docker update it did run for me

**Comment by MartijnVisser** [comment]
@JingGe I was testing a bit with a build pipeline and ran a convergence check. That actually fails. I ran `mvn clean install -Dflink.convergence.phase=install -DskipTests -U -Pcheck-convergence` which fails with:

```
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (dependency-convergence) @ flink-connector-elasticsearch-base ---
[WARNING] 
Dependency convergence error for org.apache.httpcomponents:httpcore-nio:4.4.10 paths to dependency are:
+-org.apache.flink:flink-connector-elasticsearch-base:1.16-SNAPSHOT
  +-org.elasticsearch.client:elasticsearch-rest-high-level-client:7.10.2
    +-org.elasticsearch.client:elasticsearch-rest-client:7.10.2
      +-org.apache.httpcomponents:httpasyncclient:4.1.4
        +-org.apache.httpcomponents:httpcore-nio:4.4.10
and
+-org.apache.flink:flink-connector-elasticsearch-base:1.16-SNAPSHOT
  +-org.elasticsearch.client:elasticsearch-rest-high-level-client:7.10.2
    +-org.elasticsearch.client:elasticsearch-rest-client:7.10.2
      +-org.apache.httpcomponents:httpcore-nio:4.4.12

[WARNING] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability. See above detailed error message.
```

**Comment by JingGe** [comment]
Thanks @MartijnVisser for the feedback. Like we talked offline, I will closed this PR and open a follow-up PR which will contain the fix of the dependency convergence issue.

**Comment by JingGe** [comment]
please refer to the new PR: #5

**Pull request closed without merging**
