### PR TITLE
[FLINK-31696] ElasticSearch nightly CI failure

### PR DESCRIPTION
**Pull request by reta**
ElasticSearch nightly CI failure

### CODE REVIEW

**Comment by reta** [comment]
@MartijnVisser bringing the fixes to Elasticsearch Connector :-)

**Review by MartijnVisser — APPROVED** [review]
@reta Can you include setting the version for the connector to 4.0-SNAPSHOT, given that we'll drop support for Flink 1.16 with this PR?

**Comment by reta** [comment]
> @reta Can you include setting the version for the connector to 4.0-SNAPSHOT, given that we'll drop support for Flink 1.16 with this PR?

@MartijnVisser it was done already, https://github.com/apache/flink-connector-elasticsearch/blob/main/pom.xml#L32 :)

**Review by MartijnVisser — APPROVED** [review]
LGTM, thanks @reta :)

**Comment by MartijnVisser** [comment]
Nightly triggered at https://github.com/apache/flink-connector-elasticsearch/actions/runs/4670944068

**Pull request merged**
